export enum BoardLinkPermission {
  VIEW_BOARD_LINK = 'VIEW_BOARD_LINK',
  CREATE_BOARD_LINK = 'CREATE_BOARD_LINK',
  UPDATE_BOARD_LINK = 'UPDATE_BOARD_LINK',
  REMOVE_BOARD_LINK = 'REMOVE_BOARD_LINK',
}
