export enum BoardPermission {
  VIEW_BOARD = 'VIEW_BOARD',
  CREATE_BOARD = 'CREATE_BOARD',
  UPDATE_BOARD_DESCRIPTION = 'UPDATE_BOARD_DESCRIPTION',
  UPDATE_BOARD_VISIBILITY = 'UPDATE_BOARD_VISIBILITY',
  REMOVE_BOARD = 'REMOVE_BOARD',
}
